
[core.device.print]
device_name        = true
device_api_version = true
device_type        = true

[window]
title = "Vulkan Example - Deferred shading (2016 by Sascha Willems)"

[window.dimension]
width  = 1280
height = 720

[window.cursor]
is_grab = true
is_hide = true

[core.physical]
features = ["sampler_anisotropy"]
