language: rust

rust:
- stable

script:
- cargo build --manifest-path ./gensokyo-vulkan/Cargo.toml
- cargo build --manifest-path ./gensokyo/Cargo.toml
- cargo build --manifest-path ./gensokyo-macros/Cargo.toml

- cargo build --manifest-path ./examples/Eg01.basic/Cargo.toml
- cargo build --manifest-path ./examples/Eg02.gltf/Cargo.toml
