language: rust

rust:
- stable

script:
- cargo build --manifest-path ./Cargo.toml
- cargo build --manifest-path ./examples/Eg001.triangle/Cargo.toml
- cargo build --manifest-path ./examples/Eg002.draw_index/Cargo.toml
