
[workspace]
members = [
    "hakurei",
    "hakurei-macros",

    "examples/Eg001.triangle",
    "examples/Eg002.index_buffer",
    "examples/Eg003.staging_buffer",
    "examples/Eg004.uniform_buffer",
]
