
[package]
name        = "gensokyo-macros"
version     = "0.1.0"
authors     = ["usami-renko <usami-ssc@protonmail.com>"]
edition     = "2018"
workspace   = ".."
description = "Practical macros for gensokyo and application."
