
[core.device.print]
device_name        = true
device_api_version = true
device_type        = true

[window]
title = "Vulkan Example - Push constants"

[window.dimension]
width  = 1280
height = 720

[window.cursor]
is_grab = true
is_hide = true
