[package]
name = "index_buffer"
version = "0.1.0"
authors = ["usami-renko <usami-ssc@protonmail.com>"]
description = "Use index buffer to draw an rectangle."

[dependencies]
hakurei = { path = "../.." }
