
[core.device.print]
device_name        = true
device_api_version = true
device_type        = true

[window]
title = "Vulkan Example - Runtime mip map generation"

[window.dimension]
width  = 1280
height = 720

[core.physical]
features = ["sampler_anisotropy"]

[window.cursor]
is_grab = true
is_hide = true
