
use winit::VirtualKeyCode;

pub enum HaKeycode {
    Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key0,
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    Escape,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15,
    Snapshot, Scroll, Pause, Insert, Home, Delete, End, PageDown, PageUp,
    Left, Up, Right, Down,
    Back, Return, Space, Compose, Caret, Tab,
    Numlock, Numpad0, Numpad1, Numpad2, Numpad3, Numpad4, Numpad5, Numpad6, Numpad7, Numpad8, Numpad9,
    AbntC1, AbntC2, Add, Apostrophe, Apps, At, Ax, Backslash, Calculator, Capital, Colon, Comma, Convert, Decimal, Divide, Equals, Grave, Kana, Kanji,
    LAlt, LBracket, LControl, LShift, LWin,
    RAlt, RBracket, RControl, RShift, RWin,
    Mail, MediaSelect, MediaStop, Minus, Multiply, Mute, MyComputer, NavigateForward, NavigateBackward, NextTrack, NoConvert, NumpadComma, NumpadEnter, NumpadEquals, OEM102, Period, PlayPause, Power, PrevTrack, Semicolon, Slash, Sleep, Stop, Subtract, Sysrq, Underline, Unlabeled, VolumeDown, VolumeUp, Wake, WebBack, WebFavorites, WebForward, WebHome, WebRefresh, WebSearch, WebStop, Yen,
    Copy, Paste, Cut,
}


impl From<HaKeycode> for VirtualKeyCode {
    fn from(code: HaKeycode) -> VirtualKeyCode {
        match code {
            HaKeycode::Key1 => VirtualKeyCode::Key1,
            HaKeycode::Key2 => VirtualKeyCode::Key2,
            HaKeycode::Key3 => VirtualKeyCode::Key3,
            HaKeycode::Key4 => VirtualKeyCode::Key4,
            HaKeycode::Key5 => VirtualKeyCode::Key5,
            HaKeycode::Key6 => VirtualKeyCode::Key6,
            HaKeycode::Key7 => VirtualKeyCode::Key7,
            HaKeycode::Key8 => VirtualKeyCode::Key8,
            HaKeycode::Key9 => VirtualKeyCode::Key9,
            HaKeycode::Key0 => VirtualKeyCode::Key0,
            HaKeycode::A => VirtualKeyCode::A,
            HaKeycode::B => VirtualKeyCode::B,
            HaKeycode::C => VirtualKeyCode::C,
            HaKeycode::D => VirtualKeyCode::D,
            HaKeycode::E => VirtualKeyCode::E,
            HaKeycode::F => VirtualKeyCode::F,
            HaKeycode::G => VirtualKeyCode::G,
            HaKeycode::H => VirtualKeyCode::H,
            HaKeycode::I => VirtualKeyCode::I,
            HaKeycode::J => VirtualKeyCode::J,
            HaKeycode::K => VirtualKeyCode::K,
            HaKeycode::L => VirtualKeyCode::L,
            HaKeycode::M => VirtualKeyCode::M,
            HaKeycode::N => VirtualKeyCode::N,
            HaKeycode::O => VirtualKeyCode::O,
            HaKeycode::P => VirtualKeyCode::P,
            HaKeycode::Q => VirtualKeyCode::Q,
            HaKeycode::R => VirtualKeyCode::R,
            HaKeycode::S => VirtualKeyCode::S,
            HaKeycode::T => VirtualKeyCode::T,
            HaKeycode::U => VirtualKeyCode::U,
            HaKeycode::V => VirtualKeyCode::V,
            HaKeycode::W => VirtualKeyCode::W,
            HaKeycode::X => VirtualKeyCode::X,
            HaKeycode::Y => VirtualKeyCode::Y,
            HaKeycode::Z => VirtualKeyCode::Z,
            HaKeycode::Escape => VirtualKeyCode::Escape,
            HaKeycode::F1  => VirtualKeyCode::F1,
            HaKeycode::F2  => VirtualKeyCode::F2,
            HaKeycode::F3  => VirtualKeyCode::F3,
            HaKeycode::F4  => VirtualKeyCode::F4,
            HaKeycode::F5  => VirtualKeyCode::F5,
            HaKeycode::F6  => VirtualKeyCode::F6,
            HaKeycode::F7  => VirtualKeyCode::F7,
            HaKeycode::F8  => VirtualKeyCode::F8,
            HaKeycode::F9  => VirtualKeyCode::F9,
            HaKeycode::F10 => VirtualKeyCode::F10,
            HaKeycode::F11 => VirtualKeyCode::F11,
            HaKeycode::F12 => VirtualKeyCode::F12,
            HaKeycode::F13 => VirtualKeyCode::F13,
            HaKeycode::F14 => VirtualKeyCode::F14,
            HaKeycode::F15 => VirtualKeyCode::F15,
            HaKeycode::Snapshot   => VirtualKeyCode::Snapshot,
            HaKeycode::Scroll     => VirtualKeyCode::Scroll,
            HaKeycode::Pause      => VirtualKeyCode::Pause,
            HaKeycode::Insert     => VirtualKeyCode::Insert,
            HaKeycode::Home       => VirtualKeyCode::Home,
            HaKeycode::Delete     => VirtualKeyCode::Delete,
            HaKeycode::End        => VirtualKeyCode::End,
            HaKeycode::PageDown   => VirtualKeyCode::PageDown,
            HaKeycode::PageUp     => VirtualKeyCode::PageUp,
            HaKeycode::Left       => VirtualKeyCode::Left,
            HaKeycode::Up         => VirtualKeyCode::Up,
            HaKeycode::Right      => VirtualKeyCode::Right,
            HaKeycode::Down       => VirtualKeyCode::Down,
            HaKeycode::Back       => VirtualKeyCode::Back,
            HaKeycode::Return     => VirtualKeyCode::Return,
            HaKeycode::Space      => VirtualKeyCode::Space,
            HaKeycode::Compose    => VirtualKeyCode::Compose,
            HaKeycode::Caret      => VirtualKeyCode::Caret,
            HaKeycode::Numlock    => VirtualKeyCode::Numlock,
            HaKeycode::Numpad0    => VirtualKeyCode::Numpad0,
            HaKeycode::Numpad1    => VirtualKeyCode::Numpad1,
            HaKeycode::Numpad2    => VirtualKeyCode::Numpad2,
            HaKeycode::Numpad3    => VirtualKeyCode::Numpad3,
            HaKeycode::Numpad4    => VirtualKeyCode::Numpad4,
            HaKeycode::Numpad5    => VirtualKeyCode::Numpad5,
            HaKeycode::Numpad6    => VirtualKeyCode::Numpad6,
            HaKeycode::Numpad7    => VirtualKeyCode::Numpad7,
            HaKeycode::Numpad8    => VirtualKeyCode::Numpad8,
            HaKeycode::Numpad9    => VirtualKeyCode::Numpad9,
            HaKeycode::AbntC1     => VirtualKeyCode::AbntC1,
            HaKeycode::AbntC2     => VirtualKeyCode::AbntC2,
            HaKeycode::Add        => VirtualKeyCode::Add,
            HaKeycode::Apostrophe => VirtualKeyCode::Apostrophe,
            HaKeycode::Apps       => VirtualKeyCode::Apps,
            HaKeycode::At         => VirtualKeyCode::At,
            HaKeycode::Ax         => VirtualKeyCode::Ax,
            HaKeycode::Backslash  => VirtualKeyCode::Backslash,
            HaKeycode::Calculator => VirtualKeyCode::Calculator,
            HaKeycode::Capital    => VirtualKeyCode::Capital,
            HaKeycode::Colon      => VirtualKeyCode::Colon,
            HaKeycode::Comma      => VirtualKeyCode::Comma,
            HaKeycode::Convert    => VirtualKeyCode::Convert,
            HaKeycode::Decimal    => VirtualKeyCode::Decimal,
            HaKeycode::Divide     => VirtualKeyCode::Divide,
            HaKeycode::Equals     => VirtualKeyCode::Equals,
            HaKeycode::Grave      => VirtualKeyCode::Grave,
            HaKeycode::Kana       => VirtualKeyCode::Kana,
            HaKeycode::Kanji      => VirtualKeyCode::Kanji,
            HaKeycode::LAlt       => VirtualKeyCode::LAlt,
            HaKeycode::LBracket   => VirtualKeyCode::LBracket,
            HaKeycode::LControl   => VirtualKeyCode::LControl,
            HaKeycode::LShift     => VirtualKeyCode::LShift,
            HaKeycode::LWin       => VirtualKeyCode::LWin,
            HaKeycode::Mail       => VirtualKeyCode::Mail,
            HaKeycode::MediaSelect      => VirtualKeyCode::MediaSelect,
            HaKeycode::MediaStop        => VirtualKeyCode::MediaStop,
            HaKeycode::Minus            => VirtualKeyCode::Minus,
            HaKeycode::Multiply         => VirtualKeyCode::Multiply,
            HaKeycode::Mute             => VirtualKeyCode::Mute,
            HaKeycode::MyComputer       => VirtualKeyCode::MyComputer,
            HaKeycode::NavigateForward  => VirtualKeyCode::NavigateForward,
            HaKeycode::NavigateBackward => VirtualKeyCode::NavigateBackward,
            HaKeycode::NextTrack        => VirtualKeyCode::NextTrack,
            HaKeycode::NoConvert        => VirtualKeyCode::NoConvert,
            HaKeycode::NumpadComma      => VirtualKeyCode::NumpadComma,
            HaKeycode::NumpadEnter      => VirtualKeyCode::NumpadEnter,
            HaKeycode::NumpadEquals     => VirtualKeyCode::NumpadEquals,
            HaKeycode::OEM102           => VirtualKeyCode::OEM102,
            HaKeycode::Period           => VirtualKeyCode::Period,
            HaKeycode::PlayPause        => VirtualKeyCode::PlayPause,
            HaKeycode::Power            => VirtualKeyCode::Power,
            HaKeycode::PrevTrack        => VirtualKeyCode::PrevTrack,
            HaKeycode::RAlt             => VirtualKeyCode::RAlt,
            HaKeycode::RBracket         => VirtualKeyCode::RBracket,
            HaKeycode::RControl         => VirtualKeyCode::RControl,
            HaKeycode::RShift           => VirtualKeyCode::RShift,
            HaKeycode::RWin             => VirtualKeyCode::RWin,
            HaKeycode::Semicolon        => VirtualKeyCode::Semicolon,
            HaKeycode::Slash            => VirtualKeyCode::Slash,
            HaKeycode::Sleep            => VirtualKeyCode::Sleep,
            HaKeycode::Stop             => VirtualKeyCode::Stop,
            HaKeycode::Subtract         => VirtualKeyCode::Subtract,
            HaKeycode::Sysrq            => VirtualKeyCode::Sysrq,
            HaKeycode::Tab              => VirtualKeyCode::Tab,
            HaKeycode::Underline        => VirtualKeyCode::Underline,
            HaKeycode::Unlabeled        => VirtualKeyCode::Unlabeled,
            HaKeycode::VolumeDown       => VirtualKeyCode::VolumeDown,
            HaKeycode::VolumeUp         => VirtualKeyCode::VolumeUp,
            HaKeycode::Wake             => VirtualKeyCode::Wake,
            HaKeycode::WebBack          => VirtualKeyCode::WebBack,
            HaKeycode::WebFavorites     => VirtualKeyCode::WebFavorites,
            HaKeycode::WebForward       => VirtualKeyCode::WebForward,
            HaKeycode::WebHome          => VirtualKeyCode::WebHome,
            HaKeycode::WebRefresh       => VirtualKeyCode::WebRefresh,
            HaKeycode::WebSearch        => VirtualKeyCode::WebSearch,
            HaKeycode::WebStop          => VirtualKeyCode::WebStop,
            HaKeycode::Yen              => VirtualKeyCode::Yen,
            HaKeycode::Copy             => VirtualKeyCode::Copy,
            HaKeycode::Paste            => VirtualKeyCode::Paste,
            HaKeycode::Cut              => VirtualKeyCode::Cut,
        }
    }
}
